# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=2.1.0
maven_group=cc.unilock.polylootr
archives_base_name=polylootr

# Dependencies
fabric_version=0.157.0+26.2
lootr_version=k00AgeE7
polymer_version=0.17.3+26.2
